In [1]:
import numpy as np
import pandas as pd

In [14]:
dict1={
"name":['ram','shyam','hari'],
"marks":[100,90,95],
"address":['rampur','bharatpur','chitwan']
        
}

In [15]:
df=pd.DataFrame(dict1)

In [16]:
df

    name  marks    address
0    ram    100     rampur
1  shyam     90  bharatpur
2   hari     95    chitwan

In [17]:
pd.DataFrame(dict1)

    name  marks    address
0    ram    100     rampur
1  shyam     90  bharatpur
2   hari     95    chitwan

In [18]:
df.to_csv('excelsheet.csv')